### ISSUE TITLE
Enable bookmarking a page/URL

### ISSUE THREAD

**Issue by NicHerndon** [avilkomir/react-frontend-ispel#2]
Currently, the URLs for ISPeL are http://outside2.cs.ecu.edu/browse-topics and http://outside2.cs.ecu.edu/browse-courses, regardless of which topic is selected. Thus, there's no option to bookmark a particular topic.

**Comment by avilkomir** [comment]
@NicHerndon Do you think it would be enough to have a URL with the topic ID or we need to have a possibility to go directly to the topic in a specified course?
I am trying to have something like http://localhost:3000/course/35/topic_id=23/

**Comment by NicHerndon** [comment]
That's fine. It doesn't have to be descriptive, as long as the URL can take a user to a specific page/topic.

**Comment by avilkomir** [comment]
Topic id is represented in URL and the access by course id/topic id is provided
