### ISSUE TITLE
Hamburger menu doesn't allow me to Arrow key down/up

### ISSUE THREAD

**Issue by curator8** [avilkomir/react-frontend-ispel#4]
When I highlight the topics, I still can't use the arrow keys to scroll down:
![image](https://user-images.githubusercontent.com/20135147/120840864-c2161680-c538-11eb-881e-050cac26dd2d.png)
Instead, I have to manually click to shift from topic to topic.

**Comment by avilkomir** [comment]
It was not planned to enable arrow navigation. We can discuss if it is needed during our weekly meeting
