### ISSUE TITLE
The search bar has a delay 

### ISSUE THREAD

**Issue by curator8** [avilkomir/react-frontend-ispel#6]
The search bar has a slight delay when I am typing characters into it, which causes me to mistype phrases. 
![image](https://user-images.githubusercontent.com/20135147/120895503-2f827f80-c5eb-11eb-97d1-40dd7c740550.png)

**Comment by avilkomir** [comment]
https://user-images.githubusercontent.com/46700979/120898863-dcb0c400-c5fa-11eb-864b-60c03ae0c415.mp4

It depends on your internet quality. Please see how it works for me

**Comment by avilkomir** [comment]
Anyway, I have an idea how to improve the search module. I will work on it.

**Comment by avilkomir** [comment]
@curator8 Please check if it is better now.
