### ISSUE TITLE
Cannot add another topic 

### ISSUE THREAD

**Issue by curator8** [avilkomir/react-frontend-ispel#9]
I am trying to add a temporary topic but I keep getting the error "The topic with ID ppl:py:interactive-graph already exist!"
![image](https://user-images.githubusercontent.com/20135147/121715467-ecbe1d00-caac-11eb-9d76-308dabe9905a.png)

**Comment by curator8** [comment]
There is another topic called "interactive programs" which might be giving it issues.

**Comment by avilkomir** [comment]
There was an issue with rmd file upload. The fix was implemented.

**Comment by avilkomir** [comment]
The fix was deployed on the server.
